#!/bin/bash
vim_undo="${HOME}/.vim/undo"

mkdir -p "${vim_undo}"
chmod 700 "${vim_undo}"

[[ ! -e "${HOME}/.nvim" ]] && ln -s "${HOME}/.vim" "${HOME}/.nvim"
[[ ! -e "${HOME}/.nvimrc" ]] && ln -s "${HOME}/.vimrc" "${HOME}/.nvimrc"

nvim_dir=${XDG_CONFIG_HOME:=$HOME/.config}
if [[ ! -e "$nvim_dir/nvim/init.vim" ]]; then
    mkdir -p "$nvim_dir"
    ln -s "$HOME/.vim" "$nvim_dir/nvim"
    ln -s "$HOME/.vimrc" "$nvim_dir/nvim/init.vim"
fi

vim_bundle="${HOME}/.vim/bundle"
neobundle="${vim_bundle}/neobundle.vim"
mkdir -p "$vim_bundle"
if [[ -L "$neobundle" ]]; then
    rm -f "$neobundle"
fi

if [[ ! -d "$neobundle" ]]; then
    cd "$vim_bundle"
    git clone https://github.com/Shougo/neobundle.vim.git
else
    cd "$neobundle"
    git pull origin master
fi
