#!/usr/bin/env zsh

tmpfile=$(mktemp '/tmp/terminfo.XXXXXXX')
infocmp -1 xterm-256color | grep -Ev '(sitm|ritm)=' > $tmpfile
echo '\tsitm=\E[3m,' >> $tmpfile
echo '\tritm=\E[23m,' >> $tmpfile
/usr/bin/tic $tmpfile

infocmp -1 screen-256color | grep -Ev '(sitm|ritm)=' > $tmpfile
echo '\tsitm=\E[3m,' >> $tmpfile
echo '\tritm=\E[23m,' >> $tmpfile
/usr/bin/tic $tmpfile

rm -f $tmpfile
# if [[ ${+terminfo[sitm]} -eq 0 || ${+terminfo[ritm]} -eq 0 ]]; then
#     here=$(dirname "${${(%):-%N}:A}")
#     /usr/bin/tic "$here/xterm-256color-italic.terminfo"
#     /usr/bin/tic "$here/screen-256color-italic.terminfo"
# fi
